{
 "title": "Hello Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "CPU Seconds Total",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_cpu_seconds_total{job=\"hello\"}",
     "legendFormat": "Seconds Total"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{job=\"hello\"}",
     "legendFormat": "Virtual Memory"
    },
    {
     "expr": "process_resident_memory_bytes{job=\"hello\"}",
     "legendFormat": "Resident Memory"
    }
   ]
  },
  {
   "title": "GC Collections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 0 },
   "targets": [
    {
     "expr": "python_gc_collections_total{job=\"hello\"}"
    }
   ]
  }
 ]
}